language: node_js
node_js:
    - "6"
    - "5"
before_script:
    - npm install
cache:
    directories:
        - node_modules
script: node --harmony_proxies node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js